### ISSUE TITLE
投稿系統不會顯示投稿人是誰

### ISSUE THREAD

**Issue by rschiang** [sitcon-tw/staff.sitcon.org#33]
而且 staff 好像還可以修改 ʕ •ᴥ•ʔ

**Comment by wdv4758h** [comment]
https://github.com/sitcon-tw/staff.sitcon.org/commit/77edc9fbac85a6508ac5c7228962c8bfd0e0d1c3
已在列表裡加投稿人顯示

**Comment by wdv4758h** [comment]
staff 那是想要改成只有投稿者自己可以改嗎
目前沒有對 staff 做限制

**Comment by rschiang** [comment]
或許可以限制議程組才能編輯之類的（？）
((其實也還好啦

**Comment by wdv4758h** [comment]
這 issue 是顯示投稿人
在這裡加過了 https://github.com/sitcon-tw/staff.sitcon.org/commit/77edc9fbac85a6508ac5c7228962c8bfd0e0d1c3
限制編輯部份則在 https://github.com/sitcon-tw/staff.sitcon.org/commit/7f9b8688f9645e0ab883100160eb5b1765084b26
所以 close 這 issue
