### ISSUE TITLE
Nested `form` tags is not allowed in HTML5

### ISSUE THREAD

**Issue by Inndy** [sitcon-tw/staff.sitcon.org#36]
Firefox complains about this, and one of `form` tag was disappeared.

![Screenshot of Firefox view-source](https://cloud.githubusercontent.com/assets/3402337/5973335/199854aa-a8a2-11e4-8b5c-afce2fec82a0.png)

**Comment by Inndy** [comment]
URL -> `/users/{user}/edit`

**Comment by wdv4758h** [comment]
Fixed https://github.com/sitcon-tw/staff.sitcon.org/commit/61256e42a0ab403d04e64c7e3cb2a2aed8842d7c
