### ISSUE TITLE
Suggest: API fellow RESTFUL

### ISSUE THREAD

**Issue by elct9620** [sitcon-tw/staff.sitcon.org#4]
建議 API 照 RESTFUL 的方式走，至少不要讓我都用 post 送 request 啊⋯⋯

| ACTION | METHOD |
| --- | --- |
| Read | GET |
| Create | POST |
| Update | PUT |
| Delete | DELETE |

所以如果是 Read-only 的 API 應該用 GET Method 接 Request 才對

**Comment by pellaeon** [comment]
瞄到這個 issue ，以防未來有人要用 API ，在 8cb104197d145d338b5eed827eb2ca7d2d0c08c9 裡面已經整合進 Django REST framework 了，到 `/api` 就可以看到。
