### ISSUE TITLE
沒辦法開ticket

### ISSUE THREAD

**Issue by u8961310** [sitcon-tw/staff.sitcon.org#45]
點選 「提交新議題？」會跳到首頁 
瀏覽器: chrome

**Comment by rschiang** [comment]
@u8961310 應該是權限問題。當初幫網站做的權限控管現在已經記不太得啦（被揍）

已經修正了，請再試試看。

**Comment by u8961310** [comment]
@rschiang  應該是行政組權限還沒修改，等行政組設定後我在確認一下，辛苦了

**Comment by u8961310** [comment]
@rschiang  ok 可以了，辛苦了~
