### ISSUE TITLE
Several user images cannot be loaded successfully.

### ISSUE THREAD

**Issue by yuwen41200** [sitcon-tw/staff.sitcon.org#51]
Encounter errors on website ```staff.sitcon.camp```.
Console outputs: ```GET http://staff.sitcon.camp/media/photos/{link_to_img} 404 (NOT FOUND)```
Please check if these URLs are valid, thanks.

**Comment by pellaeon** [comment]
This is probably the server's configuration issue and has nothing to do with the code.
I fixed staff.sitcon.camp 's configuration.
