### ISSUE TITLE
issue: 建立新議題和留言的時候都要等很久

### ISSUE THREAD

**Issue by pellaeon** [sitcon-tw/staff.sitcon.org#59]
我猜是因為每次都要寄完通知信才會回傳 200 ，需要檢查看看到底是怎麼回事。

**Comment by rschiang** [comment]
我想應該是XD
原本的設計是寄信時只會排進 `notifications.Message` queue 裡面，不過後來因為 Heroku 處理 cron job  的方式有變所以改成瞬發瞬寄了。 把[瞬寄的 code](https://github.com/sitcon-tw/staff.sitcon.org/blob/master/notifications/models.py#L25) 拿掉，重新加回 [`./manage.py syncmail`](https://github.com/sitcon-tw/staff.sitcon.org/blob/master/notifications/management/commands/syncmail.py) 的 cron job 應該就能解決。

**Comment by pellaeon** [comment]
如果要手動 syncmail 的話我覺得不是非常乾淨的解法，因為 crond 最密集只能到每分鐘執行一次 task ，而且這樣還會造成伺服器不必要的負載，不過可以先作為一個 workaround 。

**Comment by michael34435** [comment]
考慮再開一個service做queue server?
之前遇到這問題都是做worker的解法
參考resque、sidekiq

**Comment by rschiang** [comment]
Queue server 或是其他獨立的（常態性 listen 等待寄信）的 server 聽起來也不錯。
我是沒有試過在 Django 裡面玩 threading 啦，不過或許也是一解。XD

**Comment by azdkj532** [comment]
這部分應該不用寫在 Django 裡吧？ 我覺得用 Celery 再開一個服務來做非同步寄信就夠了。

**Comment by pellaeon** [comment]
RS 我記得這部分我們當時的討論應該是你來弄？

**Comment by wdv4758h** [comment]
先用 thread 解了，這問題屬於 I/O bound，以 Python 的 thread 就能有良好的成效，如果真的想要 Celery 這類的作法之後可以再討論。
