### ISSUE TITLE
嘗試投第二個同名的稿件時，炸了

### ISSUE THREAD

**Issue by chgu82837** [sitcon-tw/staff.sitcon.org#61]
約莫在台灣時間 12/22 4:20 左右我嘗試了很多次，都得到了乖乖...

我不是故意的啊 :no_good: 

![2015-12-22 04 25 35](https://cloud.githubusercontent.com/assets/3825526/11940629/dbdf6932-a864-11e5-8c0b-8c2475d0a37a.png)

**Comment by chgu82837** [comment]
原來你們把標題設定成 unique ...

![2015-12-22 15 48 59](https://cloud.githubusercontent.com/assets/3825526/11950552/5f12dd98-a8c4-11e5-9c67-ad75dc15221f.png)

**Comment by pellaeon** [comment]
嗨，星評應該已經跟你解釋過這問題了吧？
理論上不需要同一份稿件重複投 talk/short talk 。
因此這個 unique constraint 的設計我打算維持原樣。

若沒有問題的話就請你 close 這個 issue 囉。

**Comment by chgu82837** [comment]
OK 了解~
