### ISSUE TITLE
個人資料那裡有誤

### ISSUE THREAD

**Issue by michael34435** [sitcon-tw/staff.sitcon.org#62]
預估交通費用跟搭乘方式用手機看都一樣的。

**Comment by pcchou** [comment]
?

**Comment by michael34435** [comment]
譬如我在右邊打了120
送出後左右兩邊是顯示一樣的～

http://m.imgur.com/CVt9Pt7

**Comment by pcchou** [comment]
Hi @michael34435
應該已經修好了喔，還請你再測試看看！

（Orz 又一次沒有好好 code review 被抓到了）

**Comment by michael34435** [comment]
ok啦～
