### ISSUE TITLE
issue:個人頭像？

### ISSUE THREAD

**Issue by michael34435** [sitcon-tw/staff.sitcon.org#63]
這裡有個疑問，個人頭像是一定要加嗎

quote:

個人頭像：選填，請提供 1000 x 1000 像素以上之 JPG/PNG 圖檔或連結。

送出的時候也沒提示缺什麼資料，結果發現這欄必填....

**Comment by pcchou** [comment]
Hi，講者大頭照會用於官網、大會手冊以及議程表……等等，
可以使用任何圖片，惟請盡量提供高解析度的圖片，以免印刷品質不佳。

**Comment by pellaeon** [comment]
嗨，我是議程組長。
抱歉，CFP 的文字應該是必填，我們需要一個圖片，但是可以不用露臉，只要不違反 CoC 的圖片都可以。
